batch_size: 32
data_path: /input
es_epochs: 5
max_epochs: 30
model:
  name: UNet
  unet_params:
    bilinear: true
    depth: 5
    init_features: 64
    n_channels: 5
    n_classes: 1
    use_attention: true
    use_se: true
n_folds: 5
optimizer:
  lr: 0.0001
  weight_decay: 0.001
print_freq: 100
read_weights: null
scheduler:
  params:
    factor: 0.5
    min_lr: 1.0e-06
    patience: 2
    verbose: true
seed: 42
train_frac: 0
use_kfold: true
valid_frac: 5
