
data_path: /input
model: 
    name: UNet
    unet_params:
        init_features: 32
        depth: 5
read_weights: null
batch_size: 32
print_freq: 1000
max_epochs: 30
es_epochs: 4
seed: 42
valid_frac: 32
train_frac: 4
optimizer:
    lr: 0.0005
    weight_decay: 0.001
scheduler:
    params:
        factor: 0.316227766
        patience: 1
